# Weighted K Means Clustering   


## 1. Introduction

The Weighted K-means clustering is a new k-means clustering algorithm that can automatically weight variables based on the importance of the variables in clustering. Weighted k-means adds a new step to the basic k-means algorithm to update the variable weights based on the current partition of data. It uses a weight calculation formula that minimizes the cost function of clustering given a fixed partition of data.    



 ## 2. The Algorithm

   

I would use the original [paper](https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.652.9691&rep=rep1&type=pdf) by Joshua Zhexue Huang, Michael K. Ng, Hongqiang Rong, and Zichen Li as a reference and almost the same set of notations for the variables.   

Let $X= \{ X_{1}, \ X_2,...,\ X_n \}$ be a set of $n$ objects. Object $X_i= \{ x_{i,1}, \ x_{i,2},...,\ x_{i,m}\}$ is characterized by a set of $m$ variables. We want to partition the $n$ objects into $k$ clusters that minimizes the objective function $P$ with unknown variables $U$,$Z$ and $W$ as follows: $$  P(U,Z,W)= \sum_{l=1}^{k}\sum_{i=1}^{n}\sum_{j=1}^{m} u_{i,l} w_j^{\beta} d(x_{i,j}, z_{l,j})  $$ where,  
- $U$ is an $n \times k$ partition matrix, $u_{i,l}$ is a binary variable, and $u_{i,l}=1$ indicates that object $i$ is allocated to cluster $l$;  
- $Z= \{ Z_{1}, \ Z_2,...,\ Z_k \}$ is a set of $k$ vectors representing the centroids of the $k$ clusters;   
- $d(x_{i,j}, z_{l,j}) $ is a distance measure between object $i$ and the centroid of the cluster $l$ on the $j$th variable. We define here $d(x_{i,j}, z_{l,j}) $ as : $$d(x_{i,j}, z_{l,j})= (x_{i,j}-z_{l,j})^{2}.$$   
- $W= \{ w_{1}, \ w_2,...,\ w_m \}$ be the weights for the $m$ variables such that $\sum_{j=1}^{m} w_{j}=1$ , $0 \le w_j \le 1.$   
So to minimize the cost function $P$, we have the Weighted k-means clustering as follows:  

**Weighted k-means Algorithm**    
1. Randomly choose an initial $Z^{0}=\{Z_{1},Z_{2},...,Z_{k}\}$ and randomly generate a set of initial weights $W^{0}=[ w_{1}^{0},\ w_{2}^{0},...,\ w_{m}^{0}] \ (\sum_{j=1}^{m} w_{j}=1)$. Determine $U^{0}$ such that $P(U^{0},Z^{0},W^{0})$ is minimized. Set $t=0$ ;   
2. Let $\hat{Z}=Z^{t}$ and $\hat{W}=W^{t}$, solve problem $P(U,\hat{Z},\hat{W})$ to obtain $U^{t+1}$. If $P(U^{t+1},\hat{Z},\hat{W})=P(U^{t},\hat{Z},\hat{W})$, output $(U^{t},\hat{Z},\hat{W})$ and stop; otherwise go to step 3;   
3. Let $\hat{U}=U^{t+1}$ and $\hat{W}=W^{t}$, solve problem $P(\hat{U},Z,\hat{W})$ to obtain $Z^{t+1}$. If $P(\hat{U},Z^{t+1},\hat{W})=P(\hat{U},Z^{t},\hat{W})$, output $(\hat{U},Z^{t},\hat{W})$ and stop; otherwise go to step 4;   
4. Let $\hat{U}=U^{t+1}$ and $\hat{Z}=Z^{t+1}$, solve problem $P(\hat{U},\hat{Z},W)$ to obtain $W^{t+1}$. If $P(\hat{U},\hat{Z},W^{t+1})=P(\hat{U},\hat{Z},W^{t})$, output $(\hat{U},\hat{Z},W^{t})$ and stop; otherwise, set $t=t+1$ go to step 2.






We start by importing the necessary libraries (pandas and Numpy) and defining a function.

In [1]:
pip install colorama

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [3]:
import pandas as pd
import numpy as np
import math
import random
from colorama import Fore, Back, Style
from IPython.display import Markdown, display
def printmd(string):
    display(Markdown(string))
    
def np_ed(point_1, point_2,A):
    distance = np.sum((np.dot(A,np.transpose(np.square(np.array(point_1) - np.array(point_2))))))
    return distance




## 3. Defining the W k-Means Function

### 3.1 Initializing the first centroids, weights and determining $T$ by minimizing $P$

As the 1st step of the Weighted K Means clustering we initialize the centroid vector and randomly generate the set of initial weights. Then we determine the clusters for each data points in the first iteration.   
**Replacing $U$ by $T$**   
In the original paper, to denote the clusters for each data point in every iteration, the $n \times k$ matrix $U$ was used. The elements $u_{i,l}$ of $U$ is a binary variable, and $u_{i,l}=1$ indicates that object $i$ is allocated to cluster $l$. For brevity and ease, I use a different variable $T$ which is a $(n \times 1)$ column vector, each element of $T$ is a number from the set $\{1,2,...,k\}$ and $t_{i,1}=l$ ,$(l \in \ \{1,2,...,k\})$, means that the $i$th data point belongs to the $l$th cluster. So rewriting our cost function $P$ in terms of $T$, $$  P(T,Z,W)= \sum_{l=1}^{k}\sum_{i=1}^{n}\sum_{j=1}^{m} \mathbb{1}(t_{i,1}=l) w_j^{\beta} d(x_{i,j}, z_{l,j})  $$ where $\mathbb{1}$ is the indicator function defined as 
$$\begin{equation}
\mathbb{1}(t_{i,1}=l) =
    \begin{cases}
        1 & \text{if the $i$th data point belongs to the $l$th cluster} \\
        0 & \text{otherwise}
    \end{cases}
\end{equation}$$




### 3.2 Iteration step for the centroids and weights

Now we implement the W k-means clustering. We carry the three steps until the cost function $P$ becomes constant. In the 2nd step of the W k-means clustering, using the $Z$ and $W$ of the previous iteration we solve for the $T$ that minimizes the cost function $P$. In the following code, after every iteration for the number of data points that belong to each cluster, we get the matrix $T$, the number of data points in each cluster in that iteration and the value of $P$ as output.   
In the 3rd step of the W k-means clustering, using the $T$ and $W$ of the previous iteration we solve for the $Z$ that minimizes the cost function $P$. Solving for $Z$, we get that $P$ is minimized when $$z_{l,j}= \frac{\sum_{i=1}^{n} \mathbb{1}(t_{i,1}=l)\ x_{i,j}}{\sum_{i=1}^{n} \mathbb{1}(t_{i,1}=l)}$$where $1 \le l \le k$ and $0 \le j \le m$.  The following code gives us the new centroids and the value of $P$.   
In the 4th step of the W k-means clustering, using the $T$ and $Z$ of the previous iteration we solve for the $W$ that minimizes the cost function $P$. Solving for $W$, we get that $P$ is minimized when $$w_j= \frac{1}{\sum_{t=0}^{m-1} \left[\frac{D_j}{D_t}\right]^{\frac{1}{\beta - 1}}} \ \ \ \ \ (j\in \{0,1,2,... m-1\} \ \text{and} \ \beta=2)$$ where $$D_t= \sum_{l=1}^{k}\sum_{i=1}^{n} \mathbb{1}(t_{i,1}=l) d(x_{i,t}, z_{l,t})  $$ The following code gives us the new weights and the value of $P$.

In [4]:
def Wkmeans(X, k, max_iter=100, tol=1e-6):
    P=0
    q=1
    A=np.random.choice(X.shape[0], 3, replace=False)
    print(A)
    Z = np.array(X[A])  
    B=2                      #Selecting Beta(B)
    W=np.array([[pow(0.69,B),0,0,0],[0,pow(0.1,B),0,0],[0,0,pow(0.03,B),0], [0,0,0,pow(0.18,B)]])  #Initializing the weights
    for o in range(max_iter):
        T=np.zeros(X.shape[0])
        P1=P
        P=0
        ed=np.zeros((X.shape[0],k))
        for i in range(X.shape[0]):
            for j in range(k):
                ed[i][j] = np_ed(Z[j], X[i],W)
        np.T = np.argmin(ed, axis=1) 

        for i in range(X.shape[0]):
            P =  P + np_ed(X[i], Z[np.T[i]],W)
    
        print(Fore.LIGHTBLUE_EX,"The new clusters for the",q,"th iteration")    
        printmd("**The Matrix T :**")
        print(np.T)
        printmd("**No. of data points in 1st cluster:**")            #The new clusters in this iteration
        print(np.count_nonzero(np.T == 0))
        printmd("**No. of data points in 2nd cluster:**") 
        print(np.count_nonzero(np.T == 1))
        printmd("**No. of data points in 3rd cluster:**")
        print(np.count_nonzero(np.T == 2))  
        printmd("**Value of P:**")
        print(P,"\n")
        if (P1==P): 
            break
        
        P1=P
        P=0
        for j in range(k):
            Z[j]= np.sum(X[np.T==j],axis=0)/np.count_nonzero(np.T == j)

        for i in range(X.shape[0]):
             P=  P + np_ed(X[i], Z[np.T[i]],W)
           
        print(Fore.LIGHTBLUE_EX,"The new centroids for the",q,"th iteration")  
        printmd("**Centroids:**")
        print(Z)                                                     #The new clusters in this iteration
        printmd("**Value of P:**")
        print(P,"\n")
        if (P1==P): 
            break
    
        P1= P
        P=0
        D=np.zeros(X.shape[1])
        for i in range(X.shape[0]):
            for j in range(X.shape[1]):
                D[j] = D[j] + np.square(X[i][j]-Z[np.T[i]][j])
        D1=np.zeros(X.shape[1])
        for j in range(X.shape[1]):
            D1[j] = 1/(pow((D[j]),1/(B-1)))
        
        W=np.zeros((X.shape[1],X.shape[1]))
        for i in range(X.shape[1]):
            for j in range(X.shape[1]):
                if (i==j):
                    W[i][j]= pow(1/((pow((D[i]),1/(B-1)))*(np.sum(D1))),B)
                else:
                    W[i][j]= 0
           
        for i in range(X.shape[0]):
            P= P + np_ed(X[i], Z[np.T[i]],W)
        print(Fore.LIGHTBLUE_EX ,"The new weights for the",q,"th iteration")
        printmd("**The Weight Matrix:**")
        print(W)                                                               #The new weights in this iteration
        printmd("**Value of P:**")
        print(P,"\n") 
        if (P1==P): 
            break
        q=q+1
    print(Fore.LIGHTMAGENTA_EX,"The number of iterations:",q)

## 4. Implementing the W K-means clustering for IRIS dataset

Here I implement the Weighted K means clustering algorithm on the [IRIS dataset](https://archive.ics.uci.edu/ml/datasets/iris). The data set contains 3 classes of 50 instances each, where each class refers to a type of iris plant namely **Iris-setosa, Iris-versicolor** and **Iris-virginica**.

For the IRIS dataset, we have the no. of data points $n=150$, the number of clusters $k=3$ and the no. of variables $m=4$. So our cost function $P$ for the IRIS dataset is  $$  P(T,Z,W)= \sum_{l=1}^{3}\sum_{i=1}^{150}\sum_{j=0}^{3} \mathbb{1}(t_{i,1}=l) w_j^{\beta} d(x_{i,j}, z_{l,j})  $$

In [5]:
iris=pd.read_csv ("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data",
                   names = ["Sepal Length", "Sepal Width", "Petal Length", "Petal Width", "Class" ])  #Reading the csv file
X1 = iris.iloc[:,0:4]
y = iris.iloc[:,-1]
X=np.array(X1)
Wkmeans(X,3)

[122 148 135]
 The new clusters for the 1 th iteration


**The Matrix T :**

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 0 1 2 1
 1 1 1 1 1 1 2 2 1 1 1 0 1 1 0 1 1 1 0 0 2 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1
 1 1]


**No. of data points in 1st cluster:**

8


**No. of data points in 2nd cluster:**

137


**No. of data points in 3rd cluster:**

5


**Value of P:**

58.548166999999985 

 The new centroids for the 1 th iteration


**Centroids:**

[[7.3125     2.9875     6.0125     1.8375    ]
 [5.6919708  3.04671533 3.52919708 1.12262774]
 [7.64       3.36       6.44       2.26      ]]


**Value of P:**

34.357405958759124 

 The new weights for the 1 th iteration


**The Weight Matrix:**

[[0.05141916 0.         0.         0.        ]
 [0.         0.29275307 0.         0.        ]
 [0.         0.         0.00153288 0.        ]
 [0.         0.         0.         0.03725803]]


**Value of P:**

14.880290303667902 

 The new clusters for the 2 th iteration


**The Matrix T :**

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1
 1 0 0 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 0 1 0 0 1 0 0 2 0
 0 0 1 1 0 0 2 0 1 0 1 0 1 2 0 1 1 0 0 0 2 0 1 1 0 2 0 1 0 0 0 1 0 2 0 0 0
 1 1]


**No. of data points in 1st cluster:**

36


**No. of data points in 2nd cluster:**

107


**No. of data points in 3rd cluster:**

7


**Value of P:**

13.29606236577813 

 The new centroids for the 2 th iteration


**Centroids:**

[[6.83611111 2.96666667 5.46111111 1.91111111]
 [5.43551402 3.05420561 3.03738318 0.88598131]
 [6.97142857 3.5        6.02857143 2.31428571]]


**Value of P:**

12.017164002640575 

 The new weights for the 2 th iteration


**The Weight Matrix:**

[[0.08269843 0.         0.         0.        ]
 [0.         0.19046637 0.         0.        ]
 [0.         0.         0.00184351 0.        ]
 [0.         0.         0.         0.05431977]]


**Value of P:**

11.49786934344427 

 The new clusters for the 3 th iteration


**The Matrix T :**

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 1 1 1 0 1 1 0 1 1 1 0 1
 0 0 0 0 1 1 1 1 1 0 1 1 0 0 1 1 1 1 1 1 1 1 1 0 1 1 2 1 0 0 0 0 1 0 0 2 0
 0 0 1 0 0 0 2 0 0 2 1 0 0 2 0 0 0 0 0 0 2 0 0 0 0 2 0 0 0 0 0 1 0 2 0 0 0
 2 1]


**No. of data points in 1st cluster:**

52


**No. of data points in 2nd cluster:**

89


**No. of data points in 3rd cluster:**

9


**Value of P:**

10.510653653460848 

 The new centroids for the 3 th iteration


**Centroids:**

[[6.62307692 2.89230769 5.25769231 1.80576923]
 [5.28314607 3.10786517 2.66404494 0.73146067]
 [6.87777778 3.45555556 5.92222222 2.31111111]]


**Value of P:**

9.857327030539084 

 The new weights for the 3 th iteration


**The Weight Matrix:**

[[0.0875518  0.         0.         0.        ]
 [0.         0.15317152 0.         0.        ]
 [0.         0.         0.00242484 0.        ]
 [0.         0.         0.         0.06942935]]


**Value of P:**

9.762225627791102 

 The new clusters for the 4 th iteration


**The Matrix T :**

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 0 0 0 1 0 1 1 0 1 0 0 0 0
 0 0 0 0 0 1 1 1 1 0 1 0 0 0 1 1 1 0 1 1 1 1 1 0 1 1 2 0 0 0 0 2 1 0 0 2 0
 0 0 0 0 2 0 2 0 0 2 0 0 0 2 2 0 0 0 0 0 2 0 0 0 2 2 0 0 0 2 2 0 2 2 0 0 0
 2 0]


**No. of data points in 1st cluster:**

59


**No. of data points in 2nd cluster:**

75


**No. of data points in 3rd cluster:**

16


**Value of P:**

8.80375507412541 

 The new centroids for the 4 th iteration


**Centroids:**

[[6.40847458 2.8559322  5.05084746 1.70677966]
 [5.16266667 3.156      2.292      0.57066667]
 [6.95       3.30625    5.86875    2.26875   ]]


**Value of P:**

8.161864209475143 

 The new weights for the 4 th iteration


**The Weight Matrix:**

[[0.0747958  0.         0.         0.        ]
 [0.         0.10998403 0.         0.        ]
 [0.         0.         0.0035634  0.        ]
 [0.         0.         0.         0.11234506]]


**Value of P:**

7.926024669679442 

 The new clusters for the 5 th iteration


**The Matrix T :**

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 0 1 0 0 0 0
 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 2 0 2 0 2 2 0 2 0 2 0
 0 2 0 0 2 0 2 2 0 2 0 2 0 2 2 0 0 0 0 2 2 0 0 0 2 2 0 0 2 2 2 0 2 2 2 0 0
 2 0]


**No. of data points in 1st cluster:**

65


**No. of data points in 2nd cluster:**

60


**No. of data points in 3rd cluster:**

25


**Value of P:**

7.086023685441086 

 The new centroids for the 5 th iteration


**Centroids:**

[[6.11692308 2.82461538 4.72153846 1.56615385]
 [5.06       3.25666667 1.82       0.38166667]
 [7.012      3.164      5.908      2.204     ]]


**Value of P:**

6.018894730725921 

 The new weights for the 5 th iteration


**The Weight Matrix:**

[[0.04518654 0.         0.         0.        ]
 [0.         0.06582171 0.         0.        ]
 [0.         0.         0.00800004 0.        ]
 [0.         0.         0.         0.19485902]]


**Value of P:**

5.5995066005695 

 The new clusters for the 6 th iteration


**The Matrix T :**

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 2 0 2 0 2 2 0 2 0 2 2
 0 2 0 2 2 0 2 2 0 2 0 2 0 2 2 0 0 2 0 2 2 2 0 0 2 2 0 0 2 2 2 0 2 2 2 0 2
 2 0]


**No. of data points in 1st cluster:**

68


**No. of data points in 2nd cluster:**

52


**No. of data points in 3rd cluster:**

30


**Value of P:**

4.695562523406976 

 The new centroids for the 6 th iteration


**Centroids:**

[[6.02058824 2.77647059 4.55441176 1.46764706]
 [5.00384615 3.37692308 1.53461538 0.27307692]
 [6.89666667 3.12333333 5.81       2.19333333]]


**Value of P:**

4.278363133028229 

 The new weights for the 6 th iteration


**The Weight Matrix:**

[[0.01777756 0.         0.         0.        ]
 [0.         0.05439137 0.         0.        ]
 [0.         0.         0.01154377 0.        ]
 [0.         0.         0.         0.27668224]]


**Value of P:**

4.013318951411606 

 The new clusters for the 7 th iteration


**The Matrix T :**

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 2 0 2 2 0 2 0 2 2
 2 2 2 2 2 2 2 2 0 2 2 2 0 2 2 0 0 2 0 2 2 2 0 0 2 2 2 0 2 2 2 0 2 2 2 2 2
 2 0]


**No. of data points in 1st cluster:**

64


**No. of data points in 2nd cluster:**

50


**No. of data points in 3rd cluster:**

36


**Value of P:**

3.680610547929799 

 The new centroids for the 7 th iteration


**Centroids:**

[[5.975      2.7640625  4.4546875  1.4125    ]
 [5.006      3.418      1.464      0.244     ]
 [6.77222222 3.06388889 5.70833333 2.14444444]]


**Value of P:**

3.55241002770088 

 The new weights for the 7 th iteration


**The Weight Matrix:**

[[0.01000965 0.         0.         0.        ]
 [0.         0.04770979 0.         0.        ]
 [0.         0.         0.01139944 0.        ]
 [0.         0.         0.         0.3303466 ]]


**Value of P:**

3.495728403312413 

 The new clusters for the 8 th iteration


**The Matrix T :**

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 2 0 2 2 2 2
 2 2 2 2 2 2 2 2 0 2 2 2 0 2 2 0 2 2 0 2 2 2 0 0 2 2 2 0 2 2 2 2 2 2 2 2 2
 2 2]


**No. of data points in 1st cluster:**

57


**No. of data points in 2nd cluster:**

50


**No. of data points in 3rd cluster:**

43


**Value of P:**

3.3475704879015895 

 The new centroids for the 8 th iteration


**Centroids:**

[[5.96315789 2.75263158 4.36315789 1.36140351]
 [5.006      3.418      1.464      0.244     ]
 [6.65813953 3.03023256 5.6255814  2.09302326]]


**Value of P:**

3.2436878430729097 

 The new weights for the 8 th iteration


**The Weight Matrix:**

[[0.00729491 0.         0.         0.        ]
 [0.         0.03966783 0.         0.        ]
 [0.         0.         0.01163341 0.        ]
 [0.         0.         0.         0.36913356]]


**Value of P:**

3.2238508805548873 

 The new clusters for the 9 th iteration


**The Matrix T :**

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 2 0 2 2 2 2
 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 0 2 2 2 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


**No. of data points in 1st cluster:**

54


**No. of data points in 2nd cluster:**

50


**No. of data points in 3rd cluster:**

46


**Value of P:**

3.128316579228282 

 The new centroids for the 9 th iteration


**Centroids:**

[[5.95185185 2.74814815 4.33703704 1.33703704]
 [5.006      3.418      1.464      0.244     ]
 [6.62608696 3.0173913  5.57391304 2.07391304]]


**Value of P:**

3.107684293525227 

 The new weights for the 9 th iteration


**The Weight Matrix:**

[[0.0065619  0.         0.         0.        ]
 [0.         0.03632562 0.         0.        ]
 [0.         0.         0.01004437 0.        ]
 [0.         0.         0.         0.39461017]]


**Value of P:**

3.101840968960053 

 The new clusters for the 10 th iteration


**The Matrix T :**

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0
 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 2 0 2 2 2 2
 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 0 2 2 2 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


**No. of data points in 1st cluster:**

53


**No. of data points in 2nd cluster:**

50


**No. of data points in 3rd cluster:**

47


**Value of P:**

3.0979885576536925 

 The new centroids for the 10 th iteration


**Centroids:**

[[5.93773585 2.74339623 4.3245283  1.33018868]
 [5.006      3.418      1.464      0.244     ]
 [6.62765957 3.01702128 5.56170213 2.06595745]]


**Value of P:**

3.0955663708533807 

 The new weights for the 10 th iteration


**The Weight Matrix:**

[[0.00673232 0.         0.         0.        ]
 [0.         0.03646516 0.         0.        ]
 [0.         0.         0.01008499 0.        ]
 [0.         0.         0.         0.39258581]]


**Value of P:**

3.095508867152213 

 The new clusters for the 11 th iteration


**The Matrix T :**

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0
 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 2 0 2 2 2 2
 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 0 2 2 2 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


**No. of data points in 1st cluster:**

53


**No. of data points in 2nd cluster:**

50


**No. of data points in 3rd cluster:**

47


**Value of P:**

3.095508867152213 

 The number of iterations: 11
